
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adbhjikxuupkztmjjfeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkYmhqaWt4dXVwa3p0bWpqZmVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNzc1NjksImV4cCI6MjA1NDY1MzU2OX0.6m-xDpw5R2O6IeJTzp9fQingTlCgBW1utLBMho4UG3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
